### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ELEMENT' of undefined

### ISSUE THREAD

**Issue by litt1e-p** [lqs469/jump#10]
I got an error when `npm start`
```
(node:65745) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ELEMENT' of undefined
    at /Users/mac/Desktop/jump/index.js:43:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:65745) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:65745) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lqs469** [comment]
@litt1e-p connect device again.

**Comment by litt1e-p** [comment]
@lqs469 no, it does not work

**Comment by lqs469** [comment]
@litt1e-p be sure proxy running ?

**Comment by Lobster-King** [comment]
same error

**Comment by litt1e-p** [comment]
@lqs469 absolutely. proxy & wda works.

**Comment by litt1e-p** [comment]
```
{
    "value": "Invalid locator requested: (null)",
    "sessionId": "FE010318-FE92-4D4C-B49F-50407579C592",
    "status": 32
}
```
something wrong?
