### ISSUE TITLE
async function main() : SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by shishirui** [lqs469/jump#15]
➜  jump git:(master) ✗ npm start

> jump@1.0.0 start /Users/xxx/Desktop/tttt/tiaoyitiao/jump
 index.js                                                                                                                                                                  buffers
> babel-node index.js

/Users/rexshi/Desktop/tttt/tiaoyitiao/jump/index.js:312
async function main() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at loader (/Users/rexshi/Desktop/tttt/tiaoyitiao/jump/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rexshi/Desktop/tttt/tiaoyitiao/jump/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module.runMain (module.js:590:10)
    at Object.<anonymous> (/Users/rexshi/Desktop/tttt/tiaoyitiao/jump/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:556:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jump@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jump@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rexshi/.npm/_logs/2018-01-13T14_17_22_725Z-debug.log

**Comment by lqs469** [comment]
@shishirui [async解决方法](https://github.com/lqs469/jump/issues/2#issuecomment-355481194)

**Comment by shishirui** [comment]
已经解决，原因是nodejs的版本太老了。
