### ISSUE TITLE
通过Mac 运行之后，执行npm start，会一直蓄力，然后就飞出去了

### ISSUE THREAD

**Issue by zhangdc** [lqs469/jump#5]
通过Mac 运行之后，执行npm start，会一直蓄力，然后就飞出去了，有没有没问题的代码呢?急，在线等

**Comment by Cflelf** [comment]
我也是这个问题

**Comment by AlduinLeung** [comment]
我也是这个问题

**Comment by m00nfly** [comment]
同样的问题，npm start 后会报错，提示 变量 i 未定义，感觉像是没有定位到目标，希望作者能 修复！
```shell
> jump@1.0.0 start /Users/moon/Documents/xcode-proj/jump
> babel-node index.js

File saved.
events.js:136
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'i' of undefined
    at /Users/moon/Documents/xcode-proj/jump/index.js:148:17
    at /Users/moon/Documents/xcode-proj/jump/node_modules/get-pixels/node-pixels.js:22:5
    at exports.PNG.<anonymous> (/Users/moon/Documents/xcode-proj/jump/node_modules/pngjs/lib/png.js:74:7)
    at Object.onceWrapper (events.js:254:19)
    at exports.PNG.emit (events.js:159:13)
    at exports.PNG.<anonymous> (/Users/moon/Documents/xcode-proj/jump/node_modules/pngjs/lib/png.js:36:10)
    at module.exports.emit (events.js:159:13)
    at module.exports.ParserAsync._complete (/Users/moon/Documents/xcode-proj/jump/node_modules/pngjs/lib/parser-async.js:109:8)
    at module.exports.emit (events.js:159:13)
    at module.exports.complete (/Users/moon/Documents/xcode-proj/jump/node_modules/pngjs/lib/filter-parse-async.js:19:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jump@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jump@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/moon/.npm/_logs/2018-01-05T11_36_15_626Z-debug.log
```

**Comment by HuRKun** [comment]
执行npm start，会一直蓄力，然后就飞出去了. 打印的时间基本都是1.6s左右

**Comment by HuRKun** [comment]
我用的是iPhone 6

**Comment by zhangdc** [comment]
@HuRKun me too

**Comment by lqs469** [comment]
目前只有iphone7的参数, 如果别人借我设备和有时间的情况下会继续更新别的设备相关参数, 也万分欢迎提供参数.

**Comment by tianheng2017** [comment]
好吧！
