### ISSUE TITLE
async function main() SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by litt1e-p** [lqs469/jump#9]
I got an error when `npm start` after `npm i`
```
Users/mac/Desktop/jump/index.js:318
async function main() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at loader (/Users/mac/Desktop/jump/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mac/Desktop/jump/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module.runMain (module.js:590:10)
    at Object.<anonymous> (/Users/mac/Desktop/jump/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:556:32)
```

**Comment by litt1e-p** [comment]
fixed
